apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: docker.io/cloudbuild-example/backend:${COMMIT_ID}
          resources:
            requests:
              memory: "100Mi"
            limits:
              memory: "150Mi"
              cpu: "50m"
          livenessProbe:
            exec:
              command:
                - "curl -o /dev/null -s -w '%{http_code}' http://localhost:5000/health"
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
          ports:
            - containerPort: 5000
          imagePullPolicy: IfNotPresent