steps:
  - id: Build and Test
    name: gcr.io/cloud-builders/docker
    args:
      - compose
      - -f
      - docker-compose-gcb.yml
      - run
      - --rm
      - ${_MODULE}

  - id: Dockerfile Linter
    name: "hadolint/hadolint:v2.9.3-alpine"
    dir: "${_MODULE}"
    entrypoint: hadolint
    args: ["--failure-threshold=style", "Dockerfile"]
    waitFor: ["-"]

  - id: Build Image
    name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - '${_REGISTRY_URL}/${_PROJECT}/${_MODULE}:${SHORT_SHA}'
      - '-t'
      - "${_REGISTRY_URL}/${_PROJECT}/${_MODULE}"
      - "--cache-from"
      - "${_REGISTRY_URL}/${_PROJECT}/${_MODULE}"
      - "--build-arg"
      - "BUILDKIT_INLINE_CACHE=1"
      - "."
    dir: "${_MODULE}"
    waitFor:
      - "Build"

  - id: Trivy Scanning
    name: asia.gcr.io/glair01/gl-base/trivyscan
    entrypoint: bash
    args: ['trivyscan', '${_REGISTRY_URL}/${_PROJECT}/${_MODULE}:${SHORT_SHA}', 'scan-result.txt' ]
    waitFor:
      - 'Build Image'

  - id: Show Trivy Scan Result to PR Comment
    name: asia.gcr.io/glair01/gl-base/github
    entrypoint: /root/comment-pr-trivy.sh
    args:
      - 'scan-result.txt'
    env:
      - 'REPOSITORY=${_GITHUB_USER}/${REPO_NAME}'
      - 'COMMIT_ID=${REVISION_ID}'
      - 'TITLE=Trivy Result: ${_REGISTRY_URL}/${_PROJECT}/${_MODULE}:${SHORT_SHA}'
    secretEnv:
      - 'GH_TOKEN'

  - id: Check Trivy Result
    name: asia.gcr.io/glair01/gl-base/trivyscan
    entrypoint: /root/check.sh
    args: ['scan-result.txt']

substitutions:
  _REGISTRY_URL: docker.io/nuga99
  _PROJECT: cloudbuild-example
  _GITHUB_USER: muhammad-asn
options:
  machineType: E2_HIGHCPU_8
  env:
    - "DOCKER_BUILDKIT=1"
    - "COMPOSE_DOCKER_CLI_BUILD=1"

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/GITHUB_TOKEN/versions/latest
    env: 'GH_TOKEN'

timeout: 30m